SET C51INC=D:\Keil_v5\C51\Inc;D:\Keil_v5\C51\Inc\STC
SET C51LIB=D:\Keil_v5\C51\Lib
SET CPU_TYPE=STC15F2K60S2 Series
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"D:\Keil_v5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\i2c.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\smg.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\key.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\timer.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\hc573.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\ds18b20.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\UTRALS~1.__I"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\led.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\pcf8591.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\relay.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\Keil_v5\C51\BIN\BL51.EXE" @".\Objects\lqb16.lnp"
"D:\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\lqb16" 
